name: kepulangan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  get_storage: ^2.1.1
  permission_handler: ^11.3.1
  introduction_screen: ^3.1.7
  lottie: ^3.1.2
  iconly: ^1.0.1
  http: ^1.2.1
  dartz: ^0.10.1
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^26.1.40
  photo_view: ^0.15.0
  infinite_scroll_pagination: ^4.0.0
  path_provider: ^2.0.15
  syncfusion_flutter_pdfviewer: ^26.1.40
  flutter_downloader: ^1.10.4
  flutter: 
    sdk: flutter
  device_info_plus: ^9.1.2

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/lotties/
  uses-material-design: true

flutter_icons: 
  image_path: assets/app_logo.png
  android: true
  ios: true

flutter_native_splash: 
  android: true
  ios: true
  web: false
  color: '#ffffff'
  color_dark: '#121212'
  image: assets/splash.png
  image_dark: assets/splash.png

