name: kepulangan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19
  get_storage: ^2.1.1
  permission_handler: ^10.2.0
  introduction_screen: ^3.1.7
  lottie: ^2.3.2
  iconly: ^1.0.1
  http: ^0.13.5
  dartz: ^0.10.1
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  image_picker: ^0.8.7+2
  flutter_image_compress: ^1.1.3
  intl: ^0.18.1
  syncfusion_flutter_charts: ^21.2.6
  photo_view: ^0.14.0
  infinite_scroll_pagination: ^3.2.0
  path_provider: ^2.0.15
  syncfusion_flutter_pdfviewer: ^21.2.10
  flutter_downloader: ^1.10.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/lotties/
  uses-material-design: true

flutter_icons: 
  image_path: assets/app_logo.png
  android: true
  ios: true

flutter_native_splash: 
  android: true
  ios: true
  web: false
  color: '#ffffff'
  color_dark: '#121212'
  image: assets/splash.png
  image_dark: assets/splash.png

